<a href="https://colab.research.google.com/github/Balachandar-Ganesan/DeepLearning/blob/main/001_TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
def returnFalse():
   return 0
if returnFalse()==0:
   print("I am always False")
else:
   print("I am true Because of Decorator")

I am always False


In [16]:
def decFunc(func):
    def wrapper(*args,**kwargs):
      return 1
    return wrapper
@decFunc
def returnFalse():
   return 0
if returnFalse()==0:
   print("I am always False")
else:
   print("I am true Because of Decorator")

I am true Because of Decorator


In [24]:
class FirstClass():
  def __init__(self,name,location):
    self.name = name
    self.location = location
  def __str__(self):
    return (" I am "+ self.name + " In "+self.location)
me=FirstClass("Student", "MIT")
print(me)
#

 I am Student In MIT


In [ ]:
import tensorflow as tf

In [ ]:
two_node = tf.constant(2)
print(two_node)

In [ ]:
two_node = tf.constant(2)
another_two_node = tf.constant(2)
two_node = tf.constant(2)
tf.constant(3)

In [ ]:
two_node = tf.constant(2)
another_pointer_at_two_node = two_node
two_node = None
print( two_node)
print( another_pointer_at_two_node)

In [ ]:
two_node = tf.constant(2)
three_node = tf.constant(3)
sum_node = two_node + three_node

In [ ]:
two_node = tf.constant(2)
three_node = tf.constant(3)
sum_node = two_node + three_node
sess = tf.Session()
print( sess.run(sum_node))

In [ ]:
two_node = tf.constant(2)
three_node = tf.constant(3)
sum_node = two_node + three_node
sess = tf.Session()
print(sess.run([two_node, sum_node]))

In [ ]:
input_placeholder = tf.placeholder(tf.int32)
sess = tf.Session()
print(sess.run(input_placeholder, feed_dict={input_placeholder: 2}))

In [ ]:
count_variable = tf.get_variable("count", [])
zero_node = tf.constant(0.)
assign_node = tf.assign(count_variable, zero_node)
sess = tf.Session()
sess.run(assign_node)
print(sess.run(count_variable))


In [ ]:
const_init_node = tf.constant_initializer(0.)
count_variable = tf.get_variable("count", [], initializer=const_init_node)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(count_variable))

In [ ]:
m = tf.get_variable("m", [], initializer=tf.constant_initializer(0.))
b = tf.get_variable("b", [], initializer=tf.constant_initializer(0.))
init = tf.global_variables_initializer()

## then set up the computations
input_placeholder = tf.placeholder(tf.float32)
output_placeholder = tf.placeholder(tf.float32)

x = input_placeholder
y = output_placeholder
y_guess = m * x + b

loss = tf.square(y - y_guess)

## finally, set up the optimizer and minimization node
optimizer = tf.train.GradientDescentOptimizer(1e-3)
train_op = optimizer.minimize(loss)

### start the session
sess = tf.Session()
sess.run(init)

### perform the training loop
import random

## set up problem
true_m = random.random()
true_b = random.random()

for update_i in range(100000):
  ## (1) get the input and output
  input_data = random.random()
  output_data = true_m * input_data + true_b

  ## (2), (3), and (4) all take place within a single call to sess.run()!
  _loss, _ = sess.run([loss, train_op], feed_dict={input_placeholder: input_data, output_placeholder: output_data})
  print(update_i, _loss)

### finally, print out the values we learned for our two variables
print("True parameters:     m=%.4f, b=%.4f" % (true_m, true_b))
print( "Learned parameters:  m=%.4f, b=%.4f" % tuple(sess.run([m, b])))

In [1]:
import tensorflow as tf
two_node = tf.constant(2)
print(two_node)

tf.Tensor(2, shape=(), dtype=int32)


In [2]:
two_node = tf.constant(2)
another_two_node = tf.constant(2)
two_node = tf.constant(2)
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
two_node = tf.constant(2)
another_pointer_at_two_node = two_node
two_node = None
print(two_node)
print(another_pointer_at_two_node)

None
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
two_node = tf.constant(2)
three_node = tf.constant(3)
sum_node = two_node + three_node
print(sum_node)

tf.Tensor(5, shape=(), dtype=int32)


In [9]:
a = tf.constant([[10,10],[11.,1.]])
x = tf.constant([[1.,0.],[0.,1.]])
b = tf.Variable(12.)
y = tf.matmul(a, x) + b
print(y.numpy())

[[22. 22.]
 [23. 13.]]


In [12]:
@tf.function
def f():
    a = tf.constant([[10,10],[11.,1.]])
    x = tf.constant([[1.,0.],[0.,1.]])
    b = tf.Variable(12.)
    y = tf.matmul(a, x) + b
    print("PRINT: ", y)
    tf.print("TF-PRINT: ", y)
    return y
f()


PRINT:  Tensor("add:0", shape=(2, 2), dtype=float32)


ValueError: in user code:

    File "/tmp/ipython-input-613/336847589.py", line 5, in f  *
        b = tf.Variable(12.)

    ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information.


In [13]:
class F():
    def __init__(self):
        self._b = None

    @tf.function
    def __call__(self):
        a = tf.constant([[10, 10], [11., 1.]])
        x = tf.constant([[1., 0.], [0., 1.]])
        if self._b is None:
            self._b = tf.Variable(12.)
        y = tf.matmul(a, x) + self._b
        print("PRINT: ", y)
        tf.print("TF-PRINT: ", y)
        return y

f = F()
f()

PRINT:  Tensor("add:0", shape=(2, 2), dtype=float32)
PRINT:  Tensor("add:0", shape=(2, 2), dtype=float32)
TF-PRINT:  [[22 22]
 [23 13]]


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 22.],
       [23., 13.]], dtype=float32)>

To install Python libraries in Google Colab, you can use the `!pip install` command followed by the name of the library. For example, to install the `numpy` library, you would run the following code:

In [ ]:
!pip install numpy

After installation, you can import and use the library in your code:

In [ ]:
import numpy as np
print(np.__version__)