<a href="https://colab.research.google.com/github/Balachandar-Ganesan/DeepLearning/blob/main/008_101_TensorFlowHelloWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
var1 = tf.Variable(2706, tf.int32)
var2 = tf.Variable(2386, tf.int32)
var_sum = var1 + var2
var_sum.numpy()

np.int32(5092)

In [2]:
scalar1 = tf.Variable(95, tf.int32)
vector1 = tf.Variable([2706, 2799, 5102], \
                      tf.int32)
vector_scalar_sum = scalar1 + vector1
vector_scalar_sum.numpy()

array([2801, 2894, 5197], dtype=int32)

In [3]:
matrix1 = tf.Variable([[2706, 2799, 5102], \
                       [2386, 4089, 5932]], tf.int32)
matrix2 = tf.Variable([[5901, 1208, 645], \
                       [6235, 1098, 948]], tf.int32)
matrix3 = tf.Variable([[3908, 2339, 5520], \
                       [4544, 1978, 4729]], tf.int32)
matrix_sum = matrix1 + matrix2 + matrix3
matrix_sum.numpy()

array([[12515,  6346, 11267],
       [13165,  7165, 11609]], dtype=int32)

In [4]:
#Reshaping
array1 = tf.Variable([*range(24)])
array1

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [5]:
array1.shape.as_list()
reshape1 = tf.reshape(array1, shape=[12, 2])
reshape1.shape.as_list()
reshape2 = tf.reshape(array1, shape=[3, 4, 2])
reshape2.shape.as_list()
transpose1 = tf.transpose(reshape1)
transpose1.shape.as_list()

[2, 12]

In [6]:
#Applying Activation Functions
input1 = tf.Variable([[-0.013, 0.024, 0.06, 0.022], \
                       [0.001, -0.047, 0.039, 0.016],\
                       [0.018, 0.030, -0.021, -0.028]],\
                     tf.float32)

In [7]:
weights = tf.Variable([[19995.95], [24995.50], \
                       [36745.50], [29995.95]], \
                      tf.float32)
weights

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19995.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

In [8]:
bias = tf.Variable([[-2500.0],[-2500.0],[-2500.0]], \
                   tf.float32)
bias

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2500.],
       [-2500.],
       [-2500.]], dtype=float32)>

In [9]:
output = tf.matmul(input1,weights) + bias
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.58545],
       [-1741.7827 ],
       [-3001.75   ]], dtype=float32)>

In [10]:
output = tf.keras.activations.relu(output)
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.58545],
       [  0.     ],
       [  0.     ]], dtype=float32)>