<a href="https://colab.research.google.com/github/Balachandar-Ganesan/DeepLearning/blob/main/008_101_TensorFlowHelloWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
var1 = tf.Variable(2706, tf.int32)
var2 = tf.Variable(2386, tf.int32)
var_sum = var1 + var2
var_sum.numpy()

np.int32(5092)

In [2]:
scalar1 = tf.Variable(95, tf.int32)
vector1 = tf.Variable([2706, 2799, 5102], \
                      tf.int32)
vector_scalar_sum = scalar1 + vector1
vector_scalar_sum.numpy()

array([2801, 2894, 5197], dtype=int32)

In [3]:
matrix1 = tf.Variable([[2706, 2799, 5102], \
                       [2386, 4089, 5932]], tf.int32)
matrix2 = tf.Variable([[5901, 1208, 645], \
                       [6235, 1098, 948]], tf.int32)
matrix3 = tf.Variable([[3908, 2339, 5520], \
                       [4544, 1978, 4729]], tf.int32)
matrix_sum = matrix1 + matrix2 + matrix3
matrix_sum.numpy()

array([[12515,  6346, 11267],
       [13165,  7165, 11609]], dtype=int32)

In [4]:
#Reshaping
array1 = tf.Variable([*range(24)])
array1

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [5]:
array1.shape.as_list()
reshape1 = tf.reshape(array1, shape=[12, 2])
reshape1.shape.as_list()
reshape2 = tf.reshape(array1, shape=[3, 4, 2])
reshape2.shape.as_list()
transpose1 = tf.transpose(reshape1)
transpose1.shape.as_list()

[2, 12]

In [6]:
#Applying Activation Functions
input1 = tf.Variable([[-0.013, 0.024, 0.06, 0.022], \
                       [0.001, -0.047, 0.039, 0.016],\
                       [0.018, 0.030, -0.021, -0.028]],\
                     tf.float32)

In [7]:
weights = tf.Variable([[19995.95], [24995.50], \
                       [36745.50], [29995.95]], \
                      tf.float32)
weights

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19995.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

In [8]:
bias = tf.Variable([[-2500.0],[-2500.0],[-2500.0]], \
                   tf.float32)
bias

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2500.],
       [-2500.],
       [-2500.]], dtype=float32)>

In [9]:
output = tf.matmul(input1,weights) + bias
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.58545],
       [-1741.7827 ],
       [-3001.75   ]], dtype=float32)>

In [10]:
output = tf.keras.activations.relu(output)
output

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.58545],
       [  0.     ],
       [  0.     ]], dtype=float32)>

In [11]:
import tensorflow as tf
import numpy as np

# 1. Generate Dummy Dataset (20 records)
np.random.seed(42)
S1 = np.random.uniform(5, 10, 20)
S2 = np.random.uniform(5, 10, 20)
S3 = np.random.uniform(5, 10, 20) # Present in input but not in formula

# Formula: ((4*S1) + (3*S2) + (2*S1)) / 9.0
CGPA = ((4 * S1) + (3 * S2) + (2 * S1)) / 9.0

X = np.stack([S1, S2, S3], axis=1)
y = CGPA.reshape(-1, 1)

# 2. Build the ANN Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[3])
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.1), loss='mean_squared_error')

# 3. Train the Model
print("Training the model...")
model.fit(X, y, epochs=500, verbose=0)

# 4. Test the Model with (5, 5, 5)
test_input = np.array([[5.0, 5.0, 5.0]])
prediction = model.predict(test_input)
actual = ((4*5) + (3*5) + (2*5)) / 9.0

print(f"\nTest Input: S1=5, S2=5, S3=5")
print(f"Predicted CGPA: {prediction[0][0]:.4f}")
print(f"Actual Formula CGPA: {actual:.4f}")

# 5. Print Model Parameters (Weights and Bias)
weights, bias = model.layers[0].get_weights()
print("\n--- Model Parameters ---")
print(f"Weights (w1, w2, w3): {weights.flatten()}")
print(f"Bias (b): {bias[0]}")


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training the model...
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

Test Input: S1=5, S2=5, S3=5
Predicted CGPA: 4.9980
Actual Formula CGPA: 5.0000

--- Model Parameters ---
Weights (w1, w2, w3): [6.6705722e-01 3.3374172e-01 4.7350830e-05]
Bias (b): -0.006216984707862139


In [13]:

# 4. Test the Model with (5, 5, 5)
test_input = np.array([[5.0, 5.0, 5.0]])
prediction = model.predict(test_input)
actual = ((4*5) + (3*5) + (2*5)) / 9.0

print(f"\nTest Input: S1=5, S2=5, S3=5")
print(f"Predicted CGPA: {prediction[0][0]:.4f}")
print(f"Actual Formula CGPA: {actual:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

Test Input: S1=5, S2=5, S3=5
Predicted CGPA: 4.9980
Actual Formula CGPA: 5.0000


In [12]:
def manual_cgpa_predictor(s1, s2, s3, model):
    """
    Calculates CGPA using the weights and bias from the trained TF model.
    Formula: CGPA = (w1*s1 + w2*s2 + w3*s3) + bias
    """
    weights, bias = model.layers[0].get_weights()
    w1, w2, w3 = weights.flatten()
    b = bias[0]

    calculated_cgpa = (w1 * s1) + (w2 * s2) + (w3 * s3) + b
    return calculated_cgpa

# Example usage:
result = manual_cgpa_predictor(5, 5, 5, model)
print(f"\nFunction Output for (5,5,5): {result:.4f}")



Function Output for (5,5,5): 4.9980
